### ISSUE TITLE
Git Hooks

### ISSUE THREAD

**Issue by FranCalveyra** [Al-Fajor/printscript#46]
# TODO
- [x] Pre-commit spotless apply and test run (can commit anyways)
- [x] Pre-merge test run (can't merge a failing version)
- [x] Pull from dev-gradle
